apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven
  namespace: tekton-tasks
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Build Tools
    tekton.dev/tags: build-tool
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This Task performs a Maven deployment and, if the release parameter is set to true, makes the necessary changes to create a release version.
  workspaces:
    - name: output
      description: The workspace consisting of maven project.
  params:
    - name: registry-url
      type: string
      description: harbor repository url
    - name: profile
      type: string
      description: settings.xml nexus profile
      default: "nexus"
  steps:
    - name: mvn-goals
      image: $(params.registry-url)/maven-helm:latest
      imagePullSecrets:
      - name: quay-pull-secret
      env:
      - name: NEXUS_USER
        valueFrom:
          secretKeyRef:
            name: nexus-credentials
            key: user
      - name: NEXUS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: nexus-credentials
            key: password
      - name: NEXUS_URL
        valueFrom:
          secretKeyRef:
            name: nexus-credentials
            key: url
      workingDir: $(workspaces.output.path)
      script: |
        #!/usr/bin/env sh

        # Las variables de entorno NEXUS_USER, NEXUS_PASSWORD y NEXUS_URL son seteadas automáticamente
        # Base deployment repository se construye usando NEXUS_URL
        # baseDeploymentRepository=snapshots::default::http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/maven-snapshots
        # mvn clean deploy -P $(params.profile) -Dmaven.test.skip=true -DaltDeploymentRepository=${baseDeploymentRepository}

        mvn clean package -P $(params.profile) -Dmaven.test.skip=true
        cp $(workspaces.workspace.path)/repo/target/*.jar $(workspaces.workspace.path)/
