apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: docler.io/mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mysql_root_password"  # Cambiar por una contraseña segura
        - name: MYSQL_DATABASE
          value: "postfixadmin"
        - name: MYSQL_USER
          value: "postfixuser"
        - name: MYSQL_PASSWORD
          value: "postfix_password"  # Cambiar por una contraseña segura
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
