apiVersion: v1
kind: ConfigMap
metadata:
  name: postfixadmin-config
data:
  config.local.php: |
    <?php
    $CONF['database_type'] = 'mysqli';
    $CONF['database_host'] = 'mysql';
    $CONF['database_user'] = 'postfixuser';
    $CONF['database_password'] = 'postfix_password';
    $CONF['database_name'] = 'postfixadmin';
    $CONF['setup_password'] = '$2y$10$ZVpgMsxVppC42/SXp67JLeu5rnU3cBqacF0Ujx6FOYhmzgoYBwaz.'; 
