apiVersion: v1
kind: Service
metadata:
  name: postfix-service
  labels:
    app: postfix
spec:
  type: ClusterIP
  ports:
    - port: 25
      targetPort: smtp
      protocol: TCP
  selector:
    app: postfix
