apiVersion: v1
kind: Service
metadata:
  name: postfixadmin
  labels:
    app: postfixadmin
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: postfixadmin
