apiVersion: v1
kind: Service
metadata:
  name: postfixadmin-service
  labels:
    app: postfixadmin
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30080
      protocol: TCP
  selector:
    app: postfixadmin
