apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: cicd  # Añadido namespace
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8085  # Cambiado a 8085
        env:
        - name: JENKINS_OPTS
          value: "--httpPort=8085"  # Configuración para Jenkins
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc
