apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: docker.io/jenkins/jenkins:jdk17
        ports:
        - containerPort: 8085
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: admin-password
          mountPath: /var/jenkins_home/secrets
          readOnly: true
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc
      - name: admin-password
        secret:
          secretName: jenkins-admin-secret
          items:
          - key: JENKINS_PASSWORD
            path: JENKINS_PASSWORD
