apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonatype-registry-data
spec:
  storageClassName: sonatypestorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
