apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonatype-registry
  labels:
    app: sonatype-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonatype-registry
  template:
    metadata:
      labels:
        app: sonatype-registry
    spec:
      volumes:
        - name: registry-vol
          persistentVolumeClaim:
            claimName: sonatype-registry-data
      containers:
        - name: nexus
          image: docker.io/sonatype/nexus3:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: registry-vol
              mountPath: /nexus-data
          env:
            - name: NEXUS_CONTEXT
              value: /
            - name: JAVA_OPTS
              value: "-Dcom.sun.net.ssl.checkRevocation=false -Dcom.sun.security.enableCRLDP=false"

      

