apiVersion: apps/v1
kind: PersistentVolumeClaim
metadata:
name: sonatype-registry-data
namespace: cicd
spec:
storageClassName: sonatypestorage
accessModes:
- ReadWriteOnce
resources:
    requests:
    storage: 10Gi