apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonatype-registry
  labels:
    app: sonatype-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonatype-registry
  template:
    metadata:
      labels:
        app: sonatype-registry
    spec:
      volumes:
        - name: registry-vol
          persistentVolumeClaim:
            claimName: sonatype-registry-data
        - name: custom-ca-cert-vol
          secret:
            secretName: custom-ca-cert
      containers:
        - name: nexus
          image: docker.io/sonatype/nexus3:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: registry-vol
              mountPath: /nexus-data
            - name: custom-ca-cert-vol
              mountPath: /custom-ca
          env:
            - name: NEXUS_CONTEXT
              value: /
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - |
                    keytool -import -trustcacerts -file /custom-ca/ca.crt \
                      -alias custom-ca-cert -keystore $JAVA_HOME/lib/security/cacerts \
                      -storepass changeit -noprompt
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1"


      

