apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      serviceAccountName: postgresql-sa  # Asigna el ServiceAccount
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: postgresql
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: POSTGRES_DB
          value: "sonar"
        volumeMounts:
        - name: postgresql-storage
          mountPath: /var/lib/postgresql/data
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          runAsUser: 999  # UID del usuario postgres en el contenedor
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: postgresql-storage
        persistentVolumeClaim:
          claimName: postgresql-pvc




