apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: postgresql
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "sonar"
        - name: POSTGRES_PASSWORD
          value: "sonar_password"
        - name: POSTGRES_DB
          value: "sonar"
        - name: PGDATA  # Establece el directorio de datos de PostgreSQL
          value: "/home/postgres/pgdata"
        volumeMounts:
        - name: postgresql-storage
          mountPath: /home/postgres/pgdata
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          runAsUser: 999  # UID del usuario postgres en el contenedor
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: postgresql-storage
        persistentVolumeClaim:
          claimName: postgresql-pvc




