apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "sonar"
        - name: POSTGRES_PASSWORD
          value: "sonar_password"
        - name: POSTGRES_DB
          value: "sonar"
        volumeMounts:
        - name: postgresql-storage
          mountPath: /var/lib/postgresql/data
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0  # Ejecuta el contenedor como el usuario root
      volumes:
      - name: postgresql-storage
        persistentVolumeClaim:
          claimName: postgresql-pvc





