apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      serviceAccountName: postgresql-sa
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      initContainers:
      - name: init-permissions
        image: docker.io/busybox:latest
        command: ["sh", "-c", "mkdir -p /home/postgres/pgdata && chown -R 999:999 /home/postgres/pgdata"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          runAsUser: 999  # UID del usuario postgres
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: postgresql-storage
          mountPath: /home/postgres/pgdata
      containers:
      - name: postgresql
        image: docker.io/postgres:12.18
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: POSTGRES_DB
          value: "sonar"
        - name: PGDATA
          value: "/home/postgres/pgdata"
        volumeMounts:
        - name: postgresql-storage
          mountPath: /home/postgres/pgdata
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true  # Asegura que no se ejecute como root
          runAsUser: 999  # UID del usuario postgres en el contenedor
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: postgresql-storage
        persistentVolumeClaim:
          claimName: postgresql-pvc







