apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: sonarqube
        image: sonarqube:latest
        ports:
        - containerPort: 9000
        env:
        - name: SONARQUBE_JDBC_USERNAME
          value: "sonar"
        - name: SONARQUBE_JDBC_PASSWORD
          value: "sonar_password"
        - name: SONARQUBE_JDBC_URL
          value: "jdbc:postgresql://postgresql-service:5432/sonar"
        volumeMounts:
        - name: sonarqube-data
          mountPath: /opt/sonarqube/data
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          runAsUser: 1000  # UID del usuario no root
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: sonarqube-data
        persistentVolumeClaim:
          claimName: sonarqube-pvc

