apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar
  namespace: cicd
  labels:
    app: sonar
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonar
  template:
    metadata:
      labels:
        app: sonar
    spec:
      initContainers:
      - name: init
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
      containers:
      - name: sonarqube
        image: docker.io/sonarqube:8.9.1-community
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        env:
          - name: SONARQUBE_JDBC_URL
            valueFrom:
              configMapKeyRef:
                name: sonar-config
                key: SONARQUBE_JDBC_URL
          - name: SONARQUBE_JDBC_USERNAME
            valueFrom:
              configMapKeyRef:
                name: sonar-config
                key: SONARQUBE_JDBC_USERNAME
          - name: SONARQUBE_JDBC_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: sonar-config
                key: SONARQUBE_JDBC_PASSWORD
          - name: ES_JAVA_OPTS
            valueFrom:
              configMapKeyRef:
                name: sonar-config
                key: ES_JAVA_OPTS
        volumeMounts:
        - name: app-pvc
          mountPath: "/opt/sonarqube/data/"
          subPath: data
        - name: app-pvc
          mountPath: "/opt/sonarqube/extensions/"
          subPath: extensions
        resources:
          requests:
            memory: "1024Mi"
          limits:
            memory: "2048Mi"
      volumes:
      - name: app-pvc
        persistentVolumeClaim:
          claimName: sonarqube-pvc



