apiVersion: v1
kind: ConfigMap
metadata:
  name: sonar-config
  namespace: cicd
  labels:
    app: sonar
data:
  SONARQUBE_JDBC_URL: "jdbc:postgresql://0.0.0.0:5432/sonar_db"
  SONARQUBE_JDBC_USERNAME: "admin"
  SONARQUBE_JDBC_PASSWORD: "1234"
  ES_JAVA_OPTS: "-Duser.timezone=Asia/Jakarta -Xmx2048m"
