apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-demo
  namespace: cicd
spec:
  workspaces:
    - name: shared-workspace
  params:
  - name: revision
    type: string
    description: Rama que se clonará. Cambiar para aplicar hotfixes.
    default: "master"
  tasks:
    - name: fetch-repository
      taskRef:
        kind: task
        name: git-clone
      params:
        - name: url
          value: 
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: maven-deploy
      taskRef:
        kind: task
        name: maven
      runAfter:
        - fetch-repository
      params:
        - name: registry-url
          value: quay.io/danicuestam/maven-helm:latest        
      workspaces:
        - name: output
          workspace: shared-workspace

        