apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: git-clone-pipeline
  namespace: tekton-pipelines
spec:
  params:
    - name: revision
      type: string
      description: La rama o etiqueta a la que se debe hacer checkout.
      default: "main"
  workspaces:
    - name: shared-workspace
      description: Workspace compartido donde el repositorio será clonado.

  tasks:
    - name: clone-repository
      taskRef:
        name: git-clone-ssh
      params:
        - name: repo-url
          value: git@github.com:DaniCuesta/demo-app-labo.git
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: shared-workspace


        