apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-ejemplo
  namespace: tekton-tasks
spec:
  params:
    - name: url
      type: string
    - name: revision
      type: string
      description: La rama o etiqueta a la que se debe hacer checkout.
      default: "main"
  workspaces:
    - name: shared-workspace
      description: Workspace compartido donde el repositorio será clonado.
  tasks:
    - name: clone-repository
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: maven-build
      taskRef:
        name: maven
      runAfter:
        - clone-repository
      params:
        - name: registry-url
          value: quay.io/danicuestam
        - name: profile
          value: nexus
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: maven-upload-sonar
      taskRef:
        name: maven-upload-sonar
      runAfter:
        - maven-build
      params:
        - name: registry-url
          value: quay.io/danicuestam
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: influxdb-report
      taskRef:
        name: influxdb-report
      runAfter:
        - maven-upload-sonar
      params:
        - name: deployment-name
          value: demo
        - name: registry-url
          value: quay.io/danicuestam
        - name: sonar-url
          value: http://10.101.244.247:9000
        - name: project-key-tenant
          value: com.example:demo
        - name: influxdb-bucket
          value: SECURITY_METRICS
        - name: influxdb-url
          value: http://10.100.175.167:8086
        - name: env
          value: des
        - name: project-element
          value: backend
      workspaces:
        - name: output
          workspace: shared-workspace

        