kind: Secret
apiVersion: v1
metadata:
  name: nexus-credentials
  namespace: tekton-tasks
data:
  password: NWQwMzRiOTQtZTdhZS00YTBmLTkyNDctYzhlNWM0MzJjNTA5
  url: MTAuMTEwLjE1Mi4xOTc6ODA4MQ==
  user: YWRtaW4=
type: Opaque