apiVersion: v1
kind: Secret
metadata:
  name: quay-credentials
  namespace: kafka
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJaR0Z1YVdOMVpYTjBZVzA2Y2tNM1RUaEpObGM0Y3c9PSIKICAgIH0KICB9Cn0KCg==
