kind: Secret
apiVersion: v1
metadata:
  name: sonar-credentials
  namespace: tekton-tasks
data:
  login: YWRtaW46MTIzNA==
  token: NjEzYWMxZWZmYmY2NGRkYTAwYzk3YTg4OTVmYzJiOTk5MGQzNTNhZg==
  url: aHR0cDovLzEwLjEwMS4yNDQuMjQ3OjkwMDA=
type: Opaque