apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}
  labels:
    app.kubernetes.io/name: {{ .Values.selectorLabels.name }}
    app.kubernetes.io/instance: {{ .Values.selectorLabels.instance }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.selectorLabels.name }}
      app.kubernetes.io/instance: {{ .Values.selectorLabels.instance }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.selectorLabels.name }}
        app.kubernetes.io/instance: {{ .Values.selectorLabels.instance }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: telegraf
        image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: HOSTNAME
          value: "{{ .Values.hostname }}"
        volumeMounts:
        - name: config
          mountPath: /etc/telegraf
      volumes:
      - name: config
        configMap:
          name: {{ .Values.configMapName }}



