apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  labels:
    app.kubernetes.io/name: {{ .Values.selectorLabels.name }}
    app.kubernetes.io/instance: {{ .Values.selectorLabels.instance }}
data:
  telegraf.conf: |+
    # Correct TOML syntax
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""

    [[outputs.influxdb_v2]]
      urls = ["http://influxdb2:8086"]
      bucket = "TELEGRAF"
      token = "UxDdvLxdYdcDwLIEiER7OE"
      organization = "DES" 

    [[inputs.cpu]]
      percpu = true
      totalcpu = true
      collect_cpu_time = false
      report_active = false




