apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}
  labels:
    app.kubernetes.io/name: {{ .Values.selectorLabels.name }}
    app.kubernetes.io/instance: {{ .Values.selectorLabels.instance }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8125
    targetPort: 8125
    protocol: UDP
    name: statsd
  selector:
    app.kubernetes.io/name: {{ .Values.selectorLabels.name }}
