apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka  
spec:
  type: NodePort
  ports:
    - port: 9092
      targetPort: 9092 
      protocol: TCP
  selector:
    app: kafka-service