apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka  # Asegúrate de incluir el espacio de nombres si lo estás usando
spec:
  type: NodePort
  ports:
    - port: 9092
      targetPort: 9092  # Asegúrate de que el puerto destino coincida con el puerto del contenedor
      name: kafka-port
      protocol: TCP
  selector:
    app: kafka  # Corregido para que coincida con las etiquetas del deployment
