apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-service
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-service
  template:
    metadata:
      labels:
        app: kafka-service
    spec:
      containers:
      - name: kafka-service
        image: docker.io/bitnami/kafka:3.6.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"
        - name: KAFKA_LISTENERS
          value: "LISTENER_INTERNAL://0.0.0.0:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "LISTENER_INTERNAL://kafka-service:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "LISTENER_INTERNAL:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "LISTENER_INTERNAL"
        - name: KAFKA_BROKER_ID
          value: "1"
        volumeMounts:
        - name: kafka-storage
          mountPath: /var/lib/kafka
      - name: kafka-exporter
        image: docker.io/danielqsj/kafka-exporter:v1.2.0
        ports:
        - containerPort: 9308
        command:
        - "/bin/kafka_exporter"
        args:
        - "--kafka.server=kafka-service:9092"
        - "--kafka.version=3.6.2"
        - "--log.level=info"
      volumes:
      - name: kafka-storage
        persistentVolumeClaim:
          claimName: kafka-pvc










