apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter-service
  namespace: kafka
spec:
  selector:
    app: kafka-service
  ports:
    - protocol: TCP
      port: 9308
      targetPort: 9308
  type: ClusterIP
