apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: trivy-scan
spec:
  params:
    - name: image
      type: string
      description: "Image to scan"
  workspaces:
    - name: output
      description: "Workspace to store Trivy results"
  steps:
    - name: update-ca-certificates
      image: alpine:3.18
      volumeMounts:
        - name: zscaler-ca-cert
          mountPath: /zscaler-certs
      script: |
        #!/bin/sh
        set -xe
        # Copiar el certificado raíz personalizado al directorio de certificados
        mkdir -p /etc/ssl/certs
        cp /zscaler-certs/zscaler_root.crt /etc/ssl/certs/
        # Agregar el certificado raíz al sistema de certificados
        update-ca-certificates

    - name: trivy-scan
      image: docker.io/aquasec/trivy:latest
      env:
        - name: "DOCKER_CONFIG"
          value: "/.docker"
        - name: "SSL_CERT_FILE"
          value: "/etc/ssl/certs/ca-certificates.crt"
      volumeMounts:
        - name: docker-config
          mountPath: /.docker
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/bash
        set -xe
        image=$(params.image)
        trivy image --format json -o $(workspaces.output.path)/trivy-report.json "$image"
  volumes:
    - name: docker-config
      secret:
        secretName: quay-kaniko-credentials
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: zscaler-ca-cert
      secret:
        secretName: zscaler-ca-cert





