apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: trivy-image-scanner
spec:
  params:
    - name: image
      type: string
      description: "Image to scan"
    - name: registry-url
      description: The URL of the Harbor repository.
    - name: influxdb-url
      type: string
      description: "URL de la instancia de InfluxDB"
    - name: influxdb-org
      type: string
      description: "Nombre de la organización en InfluxDB"
    - name: influxdb-bucket
      type: string
      description: "Bucket en InfluxDB para almacenar los datos"
  workspaces:
    - name: output
      description: "Workspace para almacenar los resultados de Trivy"
  steps:
    - name: trivy-scan
      image: docker.io/aquasec/trivy:latest
      env:
        - name: "DOCKER_CONFIG"
          value: "/.docker"
        - name: "TRIVY_INSECURE"
          value: "true"
        # - name: "GITHUB_TOKEN"
        #   value: "djE6YXF1YXNlY3VyaXR5L3RyaXZ5LWRiOjE3MTUzOTU4NDkxNjY0Nzc0MTc="
      volumeMounts:
        - name: docker-config
          mountPath: /.docker
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/sh
        set -xe
        trivy image "$(params.image)"
        trivy image --format json -o $(workspaces.output.path)/trivy-report.json "$(params.image)"

    - name: trivy-scan-influxdb-report
      image: $(params.registry-url)/python-influxdb:latest
      imagePullSecrets:
      - name: quay-pull-secret
      env:
        - name: INFLUXDB_URL
          value: "$(params.influxdb-url)"
        - name: INFLUXDB_ORG
          value: "$(params.influxdb-org)"
        - name: INFLUXDB_BUCKET
          value: "$(params.influxdb-bucket)"
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-token
              key: token
        - name: TRIVY_REPORT_JSON_PATH
          value: "$(workspaces.output.path)/trivy-report.json"
        - name: IMAGE_NAME
          value: "$(params.image)"
      script: |
        #!/usr/bin/env python3
        import json
        import os
        from influxdb_client import InfluxDBClient, Point
        from influxdb_client.client.write_api import SYNCHRONOUS

        # Obtener las variables de entorno
        influxdb_url = os.getenv("INFLUXDB_URL")
        influxdb_org = os.getenv("INFLUXDB_ORG")
        influxdb_bucket = os.getenv("INFLUXDB_BUCKET")
        influxdb_token = os.getenv("INFLUXDB_TOKEN")
        trivy_report_path = os.getenv("TRIVY_REPORT_JSON_PATH")
        image_name_full = os.getenv("IMAGE_NAME")

        # Extraer solo el nombre de la aplicación o imagen
        image_name = image_name_full.split("/")[-1].split(":")[0]

        # Conectar con InfluxDB
        client = InfluxDBClient(url=influxdb_url, token=influxdb_token, org=influxdb_org)
        write_api = client.write_api(write_options=SYNCHRONOUS)

        # Leer el reporte JSON
        try:
            with open(trivy_report_path, "r") as file:
                data = json.load(file)
                trivy_report = data.get("Results", data) if isinstance(data, dict) else data
        except json.JSONDecodeError as e:
            print(f"Error al decodificar JSON: {e}")
            exit(1)

        # Contar las vulnerabilidades por severidad y tipo
        severity_count_base = {"critical": 0, "high": 0, "medium": 0, "low": 0, "unknown": 0}
        severity_count_app = {"critical": 0, "high": 0, "medium": 0, "low": 0, "unknown": 0}

        # Contar las vulnerabilidades
        for result in trivy_report:
            target_type = result["Type"]
            vulnerabilities = result.get("Vulnerabilities", [])
            severity_dict = severity_count_app if target_type == "jar" else severity_count_base
            for vuln in vulnerabilities:
                severity = vuln.get("Severity").lower()
                if severity in severity_dict:
                    severity_dict[severity] += 1

        # Calcular el total de vulnerabilidades
        total_base = sum(severity_count_base.values())
        total_app = sum(severity_count_app.values())
        total_vulnerabilities = total_base + total_app

        # Mostrar los conteos de vulnerabilidades
        print("Vulnerabilidades de la imagen base:")
        for key, value in severity_count_base.items():
            print(f"{key.capitalize()}: {value}")

        print("\nVulnerabilidades específicas de la aplicación:")
        for key, value in severity_count_app.items():
            print(f"{key.capitalize()}: {value}")

        print(f"\nTotal de vulnerabilidades: {total_vulnerabilities}")

        # Crear un punto de datos para todas las vulnerabilidades y enviarlo a InfluxDB
        point = Point("trivy_vulnerabilities") \
            .tag("image_name", image_name) \
            .field("total_base", total_base) \
            .field("total_app", total_app) \
            .field("total_vulnerabilities", total_vulnerabilities)

        # Agregar cada severidad como un campo para la imagen base
        for severity, count in severity_count_base.items():
            point = point.field(f"{severity}_base", count)

        # Agregar cada severidad como un campo para la aplicación
        for severity, count in severity_count_app.items():
            point = point.field(f"{severity}_app", count)

        # Escribir el punto con toda la información en InfluxDB
        write_api.write(bucket=influxdb_bucket, org=influxdb_org, record=point)



  volumes:
    - name: docker-config
      secret:
        secretName: quay-kaniko-credentials
        items:
          - key: .dockerconfigjson
            path: config.json








