apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: trivy-scan
  namespace: tekton-tasks
spec:
  params:
    - name: image
      type: string
      description: "Image to scan"
  workspaces:
    - name: output
      description: "The workspace to store Trivy results"
  steps:
    - name: trivy-scan
      image: docker.io/aquasec/trivy:latest
      env:
        - name: "DOCKER_CONFIG"
          value: "~/.docker/config.json"
      volumeMounts:
        - name: docker-config
          mountPath: ~/.docker
      workingDir: $(workspaces.output.path)
      script: |
        image=$(params.image)
        trivy image --format json -o $(workspaces.output.path)/trivy-report.json "$image"
  volumes:
    - name: docker-config
      secret:
        secretName: quay-kaniko-credentials
        items:
          - key: .dockerconfigjson
            path: config.json




