apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: trivy-scan
spec:
  params:
    - name: image
      type: string
      description: "Image to scan"
  workspaces:
    - name: output
      description: "Workspace to store Trivy results"
  steps:
    - name: trivy-scan
      image: docker.io/aquasec/trivy:latest
      env:
        - name: "DOCKER_CONFIG"
          value: "/.docker"
        - name: "TRIVY_INSECURE"
          value: "true"
      volumeMounts:
        - name: docker-config
          mountPath: /.docker
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/sh
        set -xe
        trivy image --format table -o $(workspaces.output.path)/trivy-report.txt "$(params.image)"
        cat $(workspaces.output.path)/trivy-report.txt
  volumes:
    - name: docker-config
      secret:
        secretName: quay-kaniko-credentials
        items:
          - key: .dockerconfigjson
            path: config.json







