apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride | quote }}
  labels:
    app: {{ .Values.service.name | quote }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type | quote }}
  selector:
    app: {{ .Values.service.name | quote }}
  ports:
  - name: {{ .Values.service.portName | quote }}
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
