apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: git-clone-pipeline-run-001  
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: git-clone-pipeline
  params:
    - name: revision
      value: "main"  # Ajusta esto a la rama que desees
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

