apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: git-clone-pipeline-run-001
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: git-clone-pipeline
  podTemplate:
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  params:
    - name: revision
      value: "main"
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi




